
import { 
  ShoppingCart, PhoneMissed, Video, Headset, Globe, Star, ShieldAlert, FileText, Home, Truck, Stethoscope, Scale,
  Users, UserX, Share2, Factory, Building, Wallet, Zap, RefreshCcw, PackageCheck, ShoppingBag, Briefcase, Gavel, 
  Landmark, PhoneForwarded, CalendarCheck, Database, MessageSquare, Mic, UserCheck, UtensilsCrossed, GraduationCap,
  ClipboardList, HardHat, HeartHandshake, PhoneIncoming, Linkedin, Mail, MessageCircle, Send, Ruler, Gift, BoxSelect,
  Timer, Repeat, Megaphone, Wrench, Droplets, FileSpreadsheet, HeartPulse, Siren, TruckIcon, Container, Anchor, PhoneCall,
  Receipt, FileSearch, HandCoins, BadgeEuro, LineChart, UserPlus, FileCheck, BellRing, Hammer, Sun, Paintbrush, Car, WrenchIcon,
  Key, Shield, Hotel, PartyPopper, ScrollText, FileClock, Network, ArrowLeftRight, Target, Search, UserMinus, Dumbbell, Laptop, 
  BookOpen, Boxes, Snowflake, FileSignature, ClipboardCheck, Thermometer, AlertTriangle, CalendarClock, HelpCircle, Languages, 
  MapPin, Share, MonitorSmartphone, PieChart, Lightbulb, Plug, School, BookMarked, Award, Baby, CreditCard, Apple, Gauge, 
  Umbrella, Map, Settings, Rocket, Ticket, LifeBuoy, AlarmClock, Cpu, Layout, BarChart, Binary, ShieldCheck, MailWarning, Workflow, Microscope,
  Trophy, Gem, Landmark as Bank, Cloud, Activity, Coffee, ClipboardType, UserCog, HeartPulse as HealthIcon, 
  Gavel as LawIcon, Lightbulb as IdeaIcon, Zap as EnergyIcon, Dumbbell as GymIcon, GraduationCap as SchoolIcon,
  Briefcase as OfficeIcon, SearchCode, Construction, Activity as Pulse, Building2, HardHat as ConstructionIcon,
  Factory as IndustryIcon, BrainCircuit, Landmark as GovIcon, Zap as PowerIcon, Heart as LifeIcon, Utensils, Hotel as HotelIcon,
  Bus, GraduationCap as EducationIcon, Newspaper, Tractor, Heart as WellnessIcon, Camera, Tv, Microscope as ResearchIcon,
  Trees, CloudRain, Wind, Landmark as FinanceIcon, Coins, Landmark as InsuranceIcon, TrendingUp, Handshake, Waves
} from 'lucide-react';

import { UseCaseCategory, UseCase } from './types';

// Add missing TrendingUp, Handshake, and Waves to ICON_MAP
export const ICON_MAP: Record<string, any> = {
  ShoppingCart, PhoneMissed, Video, Headset, Globe, Star, ShieldAlert, FileText, Home, Truck, Stethoscope, Scale,
  Users, UserX, Share2, Factory, Building, Wallet, Zap, RefreshCcw, PackageCheck, ShoppingBag, Briefcase, Gavel, 
  Landmark, PhoneForwarded, CalendarCheck, Database, MessageSquare, Mic, UserCheck, UtensilsCrossed, GraduationCap,
  ClipboardList, HardHat, HeartHandshake, PhoneIncoming, Linkedin, Mail, MessageCircle, Send, Ruler, Gift, BoxSelect,
  Timer, Repeat, Megaphone, Wrench, Droplets, FileSpreadsheet, HeartPulse, Siren, TruckIcon, Container, Anchor, PhoneCall,
  Receipt, FileSearch, HandCoins, BadgeEuro, LineChart, UserPlus, FileCheck, BellRing, Hammer, Sun, Paintbrush, Car, WrenchIcon,
  Key, Shield, Hotel, PartyPopper, ScrollText, FileClock, Network, ArrowLeftRight, Target, Search, UserMinus, Dumbbell, Laptop, 
  BookOpen, Boxes, Snowflake, FileSignature, ClipboardCheck, Thermometer, AlertTriangle, CalendarClock, HelpCircle, Languages, 
  MapPin, Share, MonitorSmartphone, PieChart, Lightbulb, Plug, School, BookMarked, Award, Baby, CreditCard, Apple, Gauge, 
  Umbrella, Map, Settings, Rocket, Ticket, LifeBuoy, AlarmClock, Cpu, Layout, BarChart, Binary, ShieldCheck, MailWarning, Workflow, Microscope,
  Trophy, Gem, Bank, Cloud, Activity, Coffee, ClipboardType, UserCog, HealthIcon, LawIcon, IdeaIcon, EnergyIcon, GymIcon, SchoolIcon, OfficeIcon, SearchCode,
  Construction, Pulse, Building2, ConstructionIcon, IndustryIcon, BrainCircuit, GovIcon, PowerIcon, LifeIcon, Utensils, HotelIcon, Bus, EducationIcon, Newspaper,
  Tractor, WellnessIcon, Camera, Tv, ResearchIcon, Trees, CloudRain, Wind, FinanceIcon, Coins, InsuranceIcon, TrendingUp, Handshake, Waves
};

export const CLIENT_LOGOS = ["Titanspear", "Enterprise", "B2B", "Automation", "Scale", "Growth"];

// Missing TECH_SPECS for the TechSpecs component
export const TECH_SPECS = [
  { label: 'Latenz (Voice)', value: '< 800ms' },
  { label: 'Erreichbarkeit', value: '24/7/365' },
  { label: 'Sprachen', value: '30+' },
  { label: 'Datenschutz', value: 'DSGVO+' },
  { label: 'Automatisierung', value: '95%' },
  { label: 'ROI (Jahr 1)', value: 'Ø 340%' }
];

const c = (
  id: string, 
  title: string, 
  pain: string, 
  dp: string, 
  sol: string, 
  ds: string, 
  icon: string, 
  prompt: string, 
  benefits: string[],
  highlight = false
): UseCase => ({
  id, title, pain, detailedPain: dp, solution: sol, detailedSolution: ds, iconName: icon, veoPrompt: prompt, benefits, highlight, simulationType: 'workflow'
});

export const USE_CASES_DATA: UseCaseCategory[] = [
  {
    id: 'trades',
    name: 'Handwerk & Bau',
    iconName: 'ConstructionIcon',
    cases: [
      c('t1', 'Dachdecker Notdienst', 'Bei Unwettern steigt das Anrufvolumen sprunghaft um 1000% an. Qualifizierte Notrufe gehen unter, Kunden wandern sofort zur Konkurrenz ab.', 'Inhaber und Gesellen befinden sich während dieser Peaks auf dem Dach und können physisch nicht abheben. Jede verpasste Anfrage bedeutet den Verlust eines lukrativen Auftrags und eines potenziellen Neukunden.', 'KI-Voice-Notdienst qualifiziert Anrufe, priorisiert schwere Schäden und bucht Einsätze live.', 'Die KI erkennt die Dringlichkeit (z.B. Wassereintritt vs. lose Ziegel), sendet dem Kunden einen SMS-Link für den Bild-Upload und prüft ERP-Kapazitäten für eine sofortige, verbindliche Zusage.', 'Hammer', 'Roofer in storm, digital cyan lines', ['100% Erreichbarkeit', 'SMS-Bild-Upload', 'Automatischer ERP-Sync'], true),
      c('t2', 'SHK Wartungs-Management', 'Manuelle Terminvereinbarung für tausende Wartungsverträge bindet hunderte unproduktive Bürostunden im Jahr.', 'Betriebe verwalten riesige Kundenstämme. Telefonate zur Terminabstimmung sind ineffizient, Kunden sind schwer erreichbar und die manuelle Routenplanung führt oft zu logistischen Sackgassen.', 'KI-Agent telefoniert Wartungslisten empathisch ab und optimiert die Einsatzplanung.', 'Das System scannt fällige Termine, ruft Kunden zur Wunschzeit an und schlägt Slots vor, die geografisch perfekt in die bestehende Tourenplanung des Technikers passen.', 'Droplets', 'HVAC technician hologram', ['85% Administrative Entlastung', '20% Wege-Effizienz', 'Proaktive Kundenbindung'], false),
      c('t3', 'Maler Sofort-Angebot', 'Lange Wartezeiten auf Angebote führen zu einer massiven Senkung der Abschlussquoten im Privatkundengeschäft.', 'Standardanfragen blockieren den Meister. Kunden, die mehr als 48h auf eine Kalkulation warten, springen oft ab oder entscheiden sich für den schnellsten Anbieter im Wettbewerb.', 'KI führt technische Erstaufnahme durch und generiert PDF-Angebote in Echtzeit.', 'Die KI fragt Maße, Wandbeschaffenheit und Farbwünsche strukturiert ab und erstellt basierend auf hinterlegten Preiskalkulationen ein fertiges Angebot am Telefon.', 'Paintbrush', 'Glowing paint droplets', ['Sofort-Angebot per Mail', 'Exakte Lead-Qualifizierung', 'Zeitersparnis Meister'], false),
      c('t4', 'Gerüstbau Logistik-Check', 'Fehlende Rückmeldungen von Baustellen führen zu teuren Leerfahrten und blockiertem Materialkapital.', 'Polierer vergessen oft, Abbautermine proaktiv zu melden. LKWs fahren leer oder dringend benötigtes Material steht ungenutzt auf abgeschlossenen Baustellen.', 'Automatisierte KI-Calls fragen Baustellenfortschritte ab und aktualisieren den ERP-Status.', 'Die KI ruft täglich Poliere an, fragt Fortschritte ab und dokumentiert Materialfreigaben für die Disposition, um Leerfahrten zu eliminieren.', 'Construction', 'Digital scaffolding structure', ['0% Leerfahrten', 'Echtzeit-Transparenz', 'Material-Umschlag +15%'], false),
      c('t5', 'Elektro First-Level Support', 'Trivialfragen von Endkunden blockieren hochbezahlte Fachkräfte am Telefon und verzögern Projekte.', 'Kunden rufen für Basiseinstellungen (Smart Home, Sicherungen) an. Fachkräfte werden bei der Montage unterbrochen, was die Fehlerquote und Projektdauer erhöht.', 'KI-Voice-Bot löst 60% der Standardfragen autonom durch Zugriff auf technisches Wissen.', 'Die KI fungiert als intelligenter Filter, kennt Handbücher und Projektfortschritte und leitet nur komplexe Störfälle an den Meister weiter.', 'Zap', 'Electric circuit boards', ['Produktivitätsschub Team', 'Sofort-Hilfe für Kunden', 'Lückenlose Dokumentation'], false)
    ]
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce & Retail',
    iconName: 'ShoppingCart',
    cases: [
      c('e1', 'High-Ticket Warenkorb-Rettung', 'Hohe Absprungraten bei Premium-Produkten (>1000€) führen zu massivem Werbebudget-Verlust im Checkout.', 'Bei teuren Anschaffungen entstehen im letzten Moment Zweifel. Standard-Retargeting-Mails werden oft ignoriert und wirken zu unpersönlich für High-Ticket Käufer.', 'Voice-KI kontaktiert Kunden 120 Sekunden nach Abbruch für eine persönliche Beratung.', 'Basierend auf dem Warenkorbinhalt bietet die KI spezifische Hilfe an, beantwortet Fragen zu Garantie/Versand und schließt den Kauf direkt am Telefon ab.', 'ShoppingCart', 'Golden cart in digital sea', ['+22% Umsatz-Recovery', 'Premium Service-Erlebnis', 'Sinkende CAC'], true),
      c('e2', 'Intelligente Retouren-Prävention', 'Hohe Retourenquoten durch Anwendungsfehler fressen Margen auf und belasten die Logistik massiv.', 'Kunden verstehen die Einrichtung oder Bedienung nicht und schicken die Ware aus Frust zurück. Ein proaktiver Support fehlt oft in der kritischen ersten Stunde.', 'KI ruft nach Zustellungsbestätigung an und klärt Setup-Fragen proaktiv.', 'Sobald das Paket zugestellt ist, meldet sich die KI: "Haben Sie Fragen zur Einrichtung?". Sie sendet bei Bedarf Video-Tutorials per SMS.', 'RefreshCcw', 'Robot inspecting package', ['-40% Retourenquote', 'Steigerung Customer Lifetime Value', 'Bessere Bewertungen'], false),
      c('e3', 'Omnichannel VIP-Concierge', 'A-Kunden erwarten im Luxussegment eine Erreichbarkeit und Personalisierung, die manuell kaum skalierbar ist.', 'Standard-Ticketsysteme enttäuschen VIP-Kunden. Markenloyalität sinkt rapide bei langsamen Reaktionen oder unpersönlichen Textbausteinen.', 'KI erkennt VIPs an der Rufnummer und bietet exklusives Personal Shopping via Voice.', 'Die KI kennt die Kaufhistorie und Stilvorlieben, reserviert Artikel in Boutiquen und managt Änderungen in flüssiger, menschlicher Konversation.', 'Gem', 'Luxury fashion digital icons', ['Maximale Kundenbindung', 'Höherer Average Order Value', 'Markendifferenzierung'], false),
      c('e4', 'Predictive Stock-Alerts', 'Kunden wandern zum Wettbewerb ab, wenn Wunschartikel nicht vorrätig sind und Benachrichtigungen nur per E-Mail erfolgen.', 'E-Mails gehen im Spam unter. Der emotionale Kaufmoment ist oft längst vorbei, wenn der Kunde die Information über die Verfügbarkeit erhält.', 'KI ruft Kunden proaktiv an, sobald Artikel lagernd sind und initiiert den Kaufprozess.', 'Die KI kontaktiert Kunden direkt: "Dein Wunschartikel ist wieder da! Soll ich ihn direkt an deine hinterlegte Adresse senden?".', 'PackageCheck', 'Digital warehouse items', ['3x höhere Conversion vs. Mail', 'Emotionaler Direktvertrieb', 'Bestands-Optimierung'], false),
      c('e5', 'Automatisierter Review-Generator', 'Zu wenige oder schlechte Bewertungen senken das Vertrauen und bremsen das organische Wachstum massiv.', 'Manuelle Bitten um Bewertung werden oft als störend empfunden oder vergessen. SMS wirken oft wie Spam und haben geringe Resonanz.', 'KI führt nach Produkterhalt empathische Feedback-Calls durch.', 'Die KI klärt die Zufriedenheit und bittet bei positivem Feedback um ein Sterne-Rating, das automatisch in das Shop-System übertragen wird.', 'Star', 'Glowing stars in binary code', ['Echter Trust-Aufbau', 'SEO-Boost durch User Content', 'Direktes Marktfeedback'], false)
    ]
  },
  {
    id: 'health',
    name: 'Gesundheitswesen',
    iconName: 'HealthIcon',
    cases: [
      c('h1', 'Praxis-Empfang Automatisierung', 'Dauerbesetzte Leitungen führen zu frustrierten Patienten und extrem gestressten MFAs am Empfang.', 'MFAs verbringen 70% ihrer Zeit mit repetitiver Administration. Privatpatienten kommen nicht durch, was zu Umsatzverlusten führt.', 'KI übernimmt die komplette Telefonzentrale inkl. Rezepten und Terminen 24/7.', 'Die KI versteht medizinische Fachbegriffe, führt eine strukturierte Triage durch und bucht direkt in medatixx/PVS-Systeme ein.', 'Pulse', 'Medical reception hologram', ['Null verpasste Anrufe', 'Stressfreier Empfang', 'Echtzeit PVS-Sync'], true),
      c('h2', 'Digitale Patienten-Anamnese', 'Die manuelle Datenaufnahme vor Ort sprengt den Zeitrahmen und sorgt für überfüllte Wartezimmer.', 'Ärzte verbringen wertvolle Behandlungszeit mit der Abfrage von Basisdaten. Patienten fühlen sich durch Formularberge im Wartezimmer gestresst.', 'KI telefoniert Patienten vor dem Termin ab und erstellt ein strukturiertes Protokoll.', 'Die KI klärt Vorerkrankungen und aktuelle Symptome am Telefon. Die Daten fließen verschlüsselt und strukturiert direkt in die Patientenakte.', 'ClipboardType', 'Heartbeat to digital file', ['+15% Patientendurchlauf', 'Höhere Behandlungsqualität', 'Rechtssichere Doku'], false),
      c('h3', 'Zahnärztlicher Recall-Service', 'Verpasste Vorsorgetermine führen zu erheblichen Umsatzverlusten und schlechterer Patienten-Prävention.', 'Patienten vergessen Termine ohne proaktive Erinnerung. Manuelles Nachtelefonieren ist für das Praxispersonal zu zeitintensiv.', 'KI telefoniert Recall-Listen autonom ab und bucht direkt neue Termine.', 'Die KI ruft empathisch an, erinnert an die Kontrolle und schlägt passende Slots vor. Die Bestätigungsquote ist 4x höher als bei SMS.', 'Star', 'Digital tooth with calendar', ['Umsatzsteigerung gesichert', 'Automatisierter Workflow', 'Bessere Präventionsquote'], false),
      c('h4', 'Pharmazeutisches Order-Management', 'Bestell-Anrufe blockieren die wichtige pharmazeutische Fachberatung in der Apotheke vor Ort.', 'PTAs müssen am Telefon Medikamentennamen buchstabieren lassen. Das verzögert die Beratung der Kunden in der Offizin.', 'KI nimmt Medikamenten-Bestellungen sicher auf und prüft die Verfügbarkeit.', 'Die KI versteht komplizierte Namen, fordert bei Bedarf Rezept-Fotos per SMS-Link an und informiert über die Abholbereitschaft.', 'LifeIcon', 'Medicine pills data stream', ['Fokus auf Vor-Ort-Beratung', 'Fehlerfreie Datenaufnahme', 'Modernes Service-Image'], false),
      c('h5', 'Physio-Kapazitätsmanagement', 'Kurzfristige Absagen führen zu unbezahlten Leerlaufzeiten für Therapeuten und Einnahmeausfällen.', 'Termine fallen aus, Ersatzpatienten können manuell nicht schnell genug erreicht werden. Therapeuten sitzen ohne Einkommen da.', 'KI telefoniert Wartelisten bei Absagen sofort in Echtzeit ab.', 'Sobald ein Slot im Kalender frei wird, kontaktiert die KI passende Patienten der Warteliste, bis der Termin wieder belegt ist.', 'Activity', 'Muscle fiber digital scan', ['100% Auslastungs-Garantie', 'Sofort-Ersatz Management', 'Umsatzsicherung'], false)
    ]
  },
  {
    id: 'realestate',
    name: 'Immobilienwirtschaft',
    iconName: 'Building2',
    cases: [
      c('r1', '24/7 Portal-Lead Qualifizierung', 'Ungefilterte Anfragen von Portalen überfordern Maklerbüros und führen zum Verlust wertvoller Leads.', 'Bei attraktiven Objekten kommen Anfragen im Minutentakt. Makler verbringen Stunden mit der Trennung von "Touristen" und echten Käufern.', 'KI ruft Leads innerhalb von 60 Sekunden an und prüft die Bonität.', 'Die KI klärt Finanzierungsbestätigungen und Suchprofile ab. Nur qualifizierte A-Interessenten erhalten das Exposé und Besichtigungstermine.', 'Building', 'Skyscraper with data lines', ['Fokus auf Top-Leads', 'Automatisches Management', 'Speed-to-Lead Rekorde'], true),
      c('r2', 'Hausverwaltung Notfall-Zentrale', 'Notfälle außerhalb der Geschäftszeiten verursachen Chaos und unkontrollierte Kosten für Eigentümer.', 'Hausverwalter sind nachts nicht erreichbar. Mieter rufen oft teure, nicht autorisierte Handwerker an. Kostenexplosion ist die Folge.', 'KI managt Notrufe autonom und beauftragt autorisierte Partnerbetriebe.', 'KI nimmt Notruf an, validiert den Schaden (z.B. Rohrbruch vs. tropfender Hahn) und beauftragt den hinterlegten Notdienst.', 'Siren', 'Glowing water ripple on plan', ['Schadensminimierung', 'Haftungssicherheit', '24/7 Mieter-Service'], false),
      c('r3', 'Interaktive Exposé-Auskunft', 'Repetitive Fragen zu Objekten blockieren das Team und verzögern den Vermarktungsprozess.', 'Interessenten stellen immer die gleichen Fragen (Haustiere, Keller, Stellplatz). Das Telefon steht nie still für triviale Auskünfte.', 'KI beantwortet detaillierte Objektfragen autonom direkt am Telefon.', 'Die KI kennt jedes Detail der Immobilie aus dem Exposé und beantwortet Fragen flüssig, bevor sie einen Besichtigungstermin vereinbart.', 'Home', 'Digital house blueprint', ['Team-Entlastung 90%', 'Schnellere Vermarktung', 'Sofortige Info-Lieferung'], false),
      c('r4', 'Schlüssel- & Handwerker-Koordination', 'Manuelle Schlüsselübergaben und Terminkoordinationen sind logistisch extrem aufwendig.', 'Handwerker, Mieter und Verwalter müssen für Termine koordiniert werden. Lange Fahrwege für Schlüsselübergaben sind unwirtschaftlich.', 'KI koordiniert Termine zwischen allen Parteien vollautomatisch.', 'Die KI telefoniert alle Beteiligten ab und stellt sicher, dass zum Termin alle vor Ort sind – inkl. automatischer SMS-Erinnerung.', 'Key', 'Glowing digital key', ['Prozess-Sicherheit', 'Logistikkosten-Senkung', 'Lückenlose Dokumentation'], false),
      c('r5', 'Eigentümer-Reporting Automatisierung', 'Der Informationsfluss zu Investoren und Eigentümern ist oft mühsam und zeitintensiv.', 'Eigentümer fordern regelmäßige Status-Updates zu Sanierungen oder Vermietungen. Diese Calls rauben Maklern wertvolle Akquise-Zeit.', 'KI gibt personalisierte Status-Berichte via Voice an Eigentümer.', 'Eigentümer rufen eine dedizierte Hotline an und erhalten von der KI den aktuellen Stand basierend auf den CRM-Einträgen.', 'LineChart', 'Bar chart growing digital', ['Investoren-Vertrauen +', 'Mehr Fokus auf Akquise', 'Vollkommene Transparenz'], false)
    ]
  },
  {
    id: 'hospitality',
    name: 'Gastronomie & Hotellerie',
    iconName: 'Utensils',
    cases: [
      c('g1', 'Intelligente Reservierungs-Zentrale', 'Anrufe während der Service-Stoßzeit können nicht entgegengenommen werden, was zu direkten Umsatzverlusten führt.', 'Gäste rufen die Konkurrenz an, wenn nicht sofort abgehoben wird. Das Team ist im Service gestresst und kann nicht telefonieren.', 'KI managt alle Tischreservierungen und beantwortet Fragen zur Karte.', 'Die KI kennt Live-Belegungen, Allergene und Parkmöglichkeiten und bucht direkt in Resmio oder OpenTable.', 'Utensils', 'Dinner plate with clock', ['Kein Tischverlust mehr', 'Enorme Team-Entlastung', 'Umsatzsteigerung'], true),
      c('g2', 'KI-Room-Service Concierge', 'Gästeanfragen in der Nacht überfordern die Minimalbesetzung an der Rezeption und führen zu Unzufriedenheit.', 'Wünsche nach zusätzlichen Handtüchern oder Drinks dauern oft zu lange. Gäste empfinden die Wartezeit als mangelhaften Service.', 'Digitaler KI-Butler am Zimmertelefon nimmt Wünsche sofort entgegen.', 'Gäste sprechen mit der KI. Wünsche werden direkt an das Housekeeping oder die Bar weitergeleitet – die Rezeption bleibt frei.', 'HotelIcon', 'Luxury hotel digital butler', ['Zufriedenere Gäste', 'Personalkosten-Optimierung', 'Einfaches Upselling'], false),
      c('g3', 'Event-Briefing Automatisierung', 'Catering- und Event-Anfragen erfordern zeitaufwendiges Nachtelefonieren für die Angebotserstellung.', 'Web-Anfragen für Hochzeiten oder Firmen-Events sind oft unvollständig. Das manuelle Nachfassen dauert oft Tage.', 'KI ruft Leads sofort an und erstellt ein fertiges Event-Briefing.', 'Innerhalb von 5 Minuten klärt die KI Personenanzahl, Budget und Technik-Bedarf und sendet ein strukturiertes PDF an den Projektleiter.', 'PartyPopper', 'Digital banquet table', ['Sales-Speed +500%', 'Präzisere Angebote', 'Automatischer Lead-Filter'], false),
      c('g4', 'Check-out Feedback-Manager', 'Wertvolles Feedback geht oft verloren oder unzufriedene Gäste posten Kritik direkt öffentlich auf Portalen.', 'Negative Erfahrungen werden erst auf Google geteilt. Das Hotel erfährt es zu spät, um intern gegenzusteuern oder zu schlichten.', 'KI ruft Gäste nach dem Check-out an und klärt die Zufriedenheit.', 'Bei Kritik leitet die KI sofort an den Manager weiter. Bei Lob bittet sie um ein Google-Review via SMS-Link.', 'Star', 'Glowing five stars', ['Aktives Reputation-Mgmt', 'Direktes Feedback-Kanal', 'Google-Rating Boost'], false),
      c('g5', 'Dynamisches Frühstücks-Leitsystem', 'Überfüllte Frühstücksräume führen zu Gast-Frustration und stressen das Servicepersonal massiv.', 'Gäste kommen oft gleichzeitig zum Buffet. Das Team ist überlastet, die Qualität des Service leidet unter dem Ansturm.', 'KI informiert Gäste proaktiv über die besten Besuchszeiten.', 'Gäste können die KI fragen: "Wann ist es im Restaurant ruhig?". Die KI analysiert Belegungsdaten und gibt Empfehlungen.', 'Coffee', 'Steaming digital cup', ['Intelligente Gast-Steuerung', 'Bessere Personal-Planung', 'Relaxte Atmosphäre'], false)
    ]
  },
  {
    id: 'finance',
    name: 'Finanzdienstleistungen',
    iconName: 'FinanceIcon',
    cases: [
      c('f1', 'Baufinanzierungs-Check', 'Interessenten müssen Basisdaten mühsam in Terminen diktieren, was die Beratungszeit ineffizient macht.', 'Die manuelle Datenaufnahme für Erstgespräche ist repetitiv und fehleranfällig. Berater verlieren Zeit für die eigentliche Strategie.', 'KI führt das Erstgespräch und erstellt ein fertiges Scoring-Dossier.', 'Die KI klärt Einkommen, Eigenkapital und Objektwert strukturiert ab und liefert dem Berater eine fertige Analyse vor dem Termin.', 'Wallet', 'Digital coins and bills house', ['Hocheffiziente Beratung', 'Höhere Abschlussquoten', 'Sofort-Feedback Kunde'], true),
      c('f2', 'Echtzeit Betrugs-Prävention', 'Kunden werden bei verdächtigen Transaktionen oft nicht rechtzeitig erreicht, was zu hohen Schäden führt.', 'Banken sperren Karten oft nur präventiv. Der Kunde steht an der Kasse und die Karte funktioniert nicht. Das sorgt für massiven Frust.', 'KI ruft Kunden sofort an und validiert Transaktionen live.', 'Die KI kontaktiert Kunden in Sekunden: "Haben Sie gerade in London bezahlt?". Bei Bestätigung wird die Karte sofort entsperrt.', 'ShieldAlert', 'Shield with warning code', ['Sicherheit & Top-Service', 'Schadensprävention', 'Kundenbindung'], false),
      c('f3', 'Wartezeitenfreie Karten-Sperrung', 'Lange Warteschleifen bei Verlust der Kreditkarte führen zu Panik und potenziellem finanziellem Schaden.', 'Kunden sind in Stresssituationen ungeduldig. Jede Minute Verzögerung erhöht das Risiko für Missbrauch und Haftungsfragen.', 'KI nimmt Sperr-Aufträge sofort und ohne jede Wartezeit an.', 'Die KI validiert die Identität per Voice-Biometrie oder Abfrage und sperrt Karten in Echtzeit in den Kernsystemen.', 'CreditCard', 'Broken digital card', ['Maximale Sicherheit', 'Null Wartezeit Support', 'Panik-Prävention'], false),
      c('f4', 'Proaktive Zins-Updates', 'Kunden verpassen lukrative Anlage-Chancen, da Berater nicht jeden Kunden individuell erreichen können.', 'Manuelle Info-Anrufe sind für das Massengeschäft zu teuer. Kunden fühlen sich bei Zinsänderungen oft nicht ausreichend betreut.', 'KI informiert Kunden proaktiv über neue Konditionen und Angebote.', 'Basierend auf dem Kontostand bietet die KI passende Produkte an und vereinbart bei Interesse einen Termin mit dem Berater.', 'TrendingUp', 'Financial graph growing', ['Automatischer Sales-Turbo', 'Skalierbare Beratung', 'Service-Vorteil'], false),
      c('f5', 'Compliance Postbox-Assistent', 'Kunden übersehen oft wichtige rechtliche Dokumente im Online-Banking, was zu Haftungsrisiken führt.', 'Rechtliche Informationen werden oft nicht gelesen. Dies erhöht die Haftungsrisiken für Banken bei regulatorischen Änderungen.', 'KI erinnert Kunden telefonisch an ungelesene Pflicht-Dokumente.', 'Die KI erklärt kurz den Inhalt (z.B. neue AGB) und bittet um Bestätigung via Sprachbefehl oder Web-Login-Link.', 'MailWarning', 'Digital envelope glowing red', ['100% Compliance Sicherheit', 'Minimierte Haftungsrisiken', 'Aktive Info-Pflicht'], false)
    ]
  },
  {
    id: 'legal',
    name: 'Rechtsberatung',
    iconName: 'LawIcon',
    cases: [
      c('l1', 'Kanzlei-Mandanten Intake', 'Sekretariate sind chronisch überlastet; jeder verpasste Anruf kann ein verpasstes lukratives Mandat bedeuten.', 'Anwaltskanzleien verlieren Mandate bei Nicht-Erreichbarkeit. Panik-Anrufer in Rechtsnotfällen warten nicht auf Rückrufe.', 'KI führt strukturierte Erstgespräche und prüft Fristen sofort.', 'Die KI fragt Daten ab, erkennt das Rechtsgebiet und prüft Fristabläufe. Der Anwalt erhält ein fertiges Dossier zur Entscheidung.', 'Scale', 'Scales of justice fiber optic', ['Sicherung neuer Mandate', 'Strukturierte Aktenführung', 'Souveräner Kanzlei-Auftritt'], true),
      c('l2', 'Automatisierter Fristen-Erinnerer', 'Mandanten liefern benötigte Unterlagen oft zu spät, was Fristabläufe und Haftungsfälle riskiert.', 'Anwälte müssen ständig hinterhertelefonieren, um Haftung zu vermeiden. Diese Zeit fehlt für die eigentliche juristische Facharbeit.', 'KI erinnert Mandanten empathisch und verbindlich an Deadlines.', 'Die KI fordert fehlende Dokumente ein, erklärt die Konsequenzen und dokumentiert jeden Kontaktversuch rechtssicher.', 'FileClock', 'Clock with digital gavel', ['Haftungsvermeidung', 'Stressfreies Team', 'Absolute Pünktlichkeit'], false),
      c('l3', 'Multilaterale Termin-Koordination', 'Gerichtstermine erfordern eine mühsame Abstimmung zwischen vielen Parteien und dem Gericht.', 'Manuelle Koordination zwischen Anwalt, Mandant, Zeugen und Gutachtern ist ein logistischer Albtraum und fehleranfällig.', 'KI koordiniert Termine autonom zwischen allen Beteiligten.', 'Die KI telefoniert alle Parteien ab, findet den kleinsten gemeinsamen Nenner und versendet Bestätigungen.', 'CalendarCheck', 'Calendar with glowing check', ['Enorme Prozess-Effizienz', 'Zeitersparnis Partner', 'Fehlerfreie Planung'], false),
      c('l4', 'Digitale Gebühren-Auskunft', 'Standardfragen zu Gebühren und Kostenrisiken blockieren Anwälte in ihrer wertvollen Beratungszeit.', 'Mandanten fragen oft: "Was kostet eine Erstberatung?". Diese repetitiven Infos rauben Zeit für die Honorararbeit an Fällen.', 'KI beantwortet Standard-Fragen zu Gebühren autonom am Telefon.', 'Die KI kennt das RVG sowie kanzleieigene Sätze und informiert Mandanten vorab über Kostenstrukturen.', 'Gavel', 'Judge gavel digital pulse', ['Kostentransparenz', 'Enorme Team-Entlastung', 'Mandanten-Vorqualifizierung'], false),
      c('l5', 'Zeugen- & Mandanten-Briefing', 'Zeugen erscheinen oft unvorbereitet oder vergessen Termine, was den Erfolg vor Gericht gefährdet.', 'Verschobene Termine kosten Kanzleien Geld und Zeit. Unvorbereitete Zeugen können den Ausgang eines Falls negativ beeinflussen.', 'KI ruft Zeugen vor dem Termin an und klärt Basis-Informationen.', 'Die KI erinnert an Ort/Zeit, gibt allgemeine Hinweise zum Ablauf und reduziert die Nervosität der Beteiligten.', 'UserCheck', 'Group of digital silhouettes', ['Höherer Prozess-Erfolg', 'Logistische Sicherheit', 'Maximale Professionalität'], false)
    ]
  },
  {
    id: 'hr',
    name: 'Personal & HR',
    iconName: 'Users',
    cases: [
      c('p1', 'High-Speed Screening-Calls', 'Hunderte Bewerbungen auf Fachkraft-Positionen überfordern die Personalabteilungen zeitlich massiv.', 'Bewerber müssen in umkämpften Märkten sofort kontaktiert werden. Wer zuerst anruft, gewinnt das Talent für sein Unternehmen.', 'KI führt Erst-Interviews innerhalb von 5 Minuten nach Bewerbungseingang.', 'Die KI prüft Soft-Skills, Gehaltsvorstellungen und Verfügbarkeiten und bucht bei Eignung direkt das Probearbeiten.', 'UserPlus', 'Digital human silhouettes', ['Hiring-Speed +400%', 'Keine verlorenen Talente', 'Objektive Bewerber-Auswahl'], true),
      c('p2', 'Digitaler Onboarding-Assistent', 'Neue Mitarbeiter haben in der ersten Woche viele Fragen, während das Team im Tagesgeschäft voll ausgelastet ist.', 'Standardfragen zu IT, Benefits oder Abläufen rauben Kollegen die Zeit. Ein mangelhaftes Onboarding senkt die Mitarbeiterbindung.', 'KI begleitet neue Mitarbeiter per Voice-Coaching durch die erste Woche.', 'Der Mitarbeiter kann jederzeit fragen: "Wie richte ich das VPN ein?". Die KI antwortet basierend auf dem Firmen-Wiki.', 'UserCheck', 'Glowing person in network', ['Schnellere Produktivität', 'Enorme Team-Entlastung', 'Modernes Mitarbeiter-Erlebnis'], false),
      c('p3', 'Anonymer Stimmungs-Check', 'Fluktuationsraten steigen oft, weil Probleme in der Belegschaft zu spät oder gar nicht erkannt werden.', 'Mitarbeitergespräche finden zu selten statt. Unzufriedenheit brodelt oft unbemerkt unter der Oberfläche, bis gekündigt wird.', 'KI führt kurze, anonymisierte Feedback-Calls im gesamten Team durch.', 'Die KI klärt die Stimmung und liefert dem Management aggregierte Trends ohne Namenennung zur Kulturverbesserung.', 'HeartPulse', 'Digital heart monitor', ['Kündigungs-Prävention', 'Echte Insights für Führung', 'Kultur-Boost'], false),
      c('p4', 'Automatisierte Schicht-Börse', 'Kurzfristige Personalausfälle in Pflege oder Produktion führen zu operativem Chaos und hohem Stress.', 'Stationsleiter müssen oft nachts dutzende Kollegen abtelefonieren, um Ersatz zu finden. Das ist eine enorme psychische Belastung.', 'KI telefoniert den Springer-Pool bei Ausfällen in Sekunden autonom ab.', 'Sobald eine Krankmeldung eingeht, ruft die KI verfügbare Kräfte an, bis die Schicht wieder voll besetzt ist.', 'Workflow', 'Connecting nodes glowing', ['Sichere Schichtplanung', 'Extrem entlastetes Personal', 'Höhere Ausfallsicherheit'], false),
      c('p5', 'KI-gestützte Exit-Interviews', 'Ehrliches Feedback bei Kündigungen fehlt oft, da Mitarbeiter gegenüber Vorgesetzten gehemmt sind.', 'Wichtige Insights über strukturelle Probleme gehen verloren. Unternehmen können ohne Daten ihre Fluktuation nicht senken.', 'KI führt neutrale und strukturierte Austrittsgespräche am Telefon.', 'Die KI sammelt wertvolle Daten über Kündigungsgründe und Arbeitsbedingungen zur systematischen Verbesserung der HR-Strategie.', 'UserMinus', 'Person silhouette fading', ['Senkung der Fluktuation', 'Ehrliche Datengrundlage', 'Prozess-Optimierung'], false)
    ]
  },
  {
    id: 'industry',
    name: 'Industrie & Fertigung',
    iconName: 'IndustryIcon',
    cases: [
      c('i1', 'Automatisierte Ersatzteil-Order', 'Die manuelle Erfassung von komplexen Teilenummern am Telefon ist extrem fehleranfällig und teuer.', 'Techniker diktieren lange Nummern unter Zeitdruck. Fehler führen zu Falschlieferungen und kostspieligen Maschinenstillständen.', 'KI erkennt Seriennummern via Sprache fehlerfrei und bucht direkt in SAP.', 'Die KI erkennt technische Fachbegriffe präzise und bestätigt die Verfügbarkeit live direkt im Gespräch.', 'Settings', 'Gears and mechanical parts', ['Null Fehlerquote Order', 'Weniger Maschinenstillstand', 'Automatischer Innendienst'], true),
      c('i2', 'KI-Wartungs-Diktat', 'Wartungsberichte werden oft spät, unleserlich oder lückenhaft erstellt, was die Abrechnung verzögert.', 'Das Tippen an Maschinen ist mühsam. Wichtige Details werden vergessen, was die Dokumentationsqualität und Faktura gefährdet.', 'Techniker diktiert den Bericht live während der Arbeit an die KI.', 'Die KI erstellt ein strukturiertes Protokoll aus dem Diktat und bucht Materialverbräuche direkt auf den entsprechenden Auftrag.', 'Wrench', 'Technician with speech bubbles', ['Präzise Dokumentation', 'Beschleunigte Faktura', 'Höhere Techniker-Laufzeit'], false),
      c('i3', 'Sprachgesteuerter Störungs-Melder', 'Die Kommunikation bei Linienstopps ist oft zu langsam, was den Ausschuss und die Ausfallkosten erhöht.', 'Mitarbeiter müssen oft zum PC laufen für eine Meldung. In dieser Zeit läuft fehlerhafter Ausschuss weiter vom Band.', 'KI-Zentrale nimmt Sprachmeldungen an und alarmiert die Instandhaltung.', 'Ein Sprachbefehl genügt: "Störung Linie 4". Die KI informiert die Technik per Push und stoppt bei Bedarf die Anlage.', 'AlertTriangle', 'Red warning signals on line', ['Ausschuss-Reduktion', 'Minimale Reaktionszeit', 'Intuitivste Bedienung'], false),
      c('i4', 'Safety-Compliance Check', 'Sicherheitsunterweisungen und tägliche Checks werden im Stress der Produktion oft vernachlässigt.', 'Manuelle Kontrollen sind zeitintensiv. Das Haftungsrisiko bei Arbeitsunfällen steigt massiv ohne lückenlose Prüfung.', 'KI prüft den Sicherheitsstatus per Voice-Check-in vor Schichtbeginn.', 'Die KI ruft Mitarbeiter an und klärt PSA-Status sowie aktuelle Gefahrenquellen strukturiert und dokumentiert ab.', 'ShieldCheck', 'Digital safety helmet', ['Aktive Unfallvermeidung', '100% Rechtssicherheit', 'Audit-Ready Doku'], false),
      c('i5', 'KI-gesteuerte Logistik-Pforte', 'LKWs stauen sich an der Werkseinfahrt durch zeitintensive manuelle Anmeldeprozesse und Bürokratie.', 'Manuelle Anmeldungen von Fahrern dauern zu lange. Lieferzeitfenster werden verpasst, was die gesamte Produktionskette stört.', 'KI übernimmt den kompletten LKW-Check-in per Sprach-Terminal.', 'Die KI prüft Lieferpapiere via OCR, validiert Lade-IDs und gibt Schranken-Codes via Voice durch – in über 30 Sprachen.', 'TruckIcon', 'Truck driving on data highway', ['Schnellerer Hof-Durchlauf', 'Enorme Personal-Ersparnis', 'Keine Staus an Pforten'], false)
    ]
  },
  {
    id: 'insurance',
    name: 'Versicherungswirtschaft',
    iconName: 'InsuranceIcon',
    cases: [
      c('v1', 'Skalierbare Schaden-Hotline', 'Bei Massenschäden (z.B. Hagel) sind menschliche Hotlines sofort überlastet und Kunden frustriert.', 'Kunden warten oft Stunden für eine einfache Schadensmeldung. Die Frustration senkt die Markenbindung und sorgt für Abwanderung.', 'KI nimmt hunderte Schadenmeldungen gleichzeitig ohne Wartezeit an.', 'Die KI nimmt den Schaden strukturiert auf, fordert Fotos via SMS-Link an und leitet Kleinschäden sofort zur Regulierung ein.', 'ShieldCheck', 'Car with digital shield', ['Unbegrenzt Skalierbar', 'Sekunden-Regulierung', 'Höchste Kundenzufriedenheit'], true),
      c('v2', 'Automatisierter Bedarfs-Check', 'Kunden wissen oft nicht, ob sie ausreichend versichert sind, was zu gefährlicher Unterversicherung führt.', 'Das Massengeschäft kann von Maklern nicht individuell betreut werden. Potenzielle Deckungslücken bleiben unentdeckt.', 'KI analysiert den Bedarf telefonisch und bietet passende Upgrades an.', 'Die KI klärt neue Lebensumstände (z.B. Hauskauf) ab und passt die Deckungssummen automatisiert und rechtssicher an.', 'FileSearch', 'Magnifying glass on document', ['Massiver Umsatz-Uplift', 'Haftungsvermeidung Makler', 'Top Service-Vorteil'], false),
      c('v3', 'Empathische Zahlungserinnerung', 'Standardmäßiges Mahnwesen ist unpersönlich und führt oft zur unnötigen Kündigung von Verträgen.', 'Harte Mahnungen wirken oft bedrohlich auf Kunden in temporären Engpässen. Kunden kündigen eher, als den Dialog zu suchen.', 'KI ruft bei Zahlungsverzug empathisch an und bietet Lösungen.', 'Die KI klärt Gründe für den Verzug und vereinbart Ratenzahlungen oder Lastschrift-Updates direkt im Gespräch.', 'BadgeEuro', 'Euro sign digital pulse', ['Geringere Stornoquoten', 'Bessere Liquidität', 'Starke Kundenbindung'], false),
      c('v4', 'KI-Datenbereinigungs Assistent', 'Umzüge werden oft nicht gemeldet; teure Post-Rückläufer belasten das Budget und die Administration.', 'Rückläufer kosten Porto und enormen Aufwand. Kunden sind bei wichtigen rechtlichen Infos nicht erreichbar.', 'KI klärt neue Adressdaten bei Unstimmigkeiten proaktiv ab.', 'Erkennt das System einen Post-Rückläufer, ruft die KI den Kunden an und fragt nach der aktuellen Adresse oder E-Mail.', 'MapPin', 'Location pin digital ripple', ['100% Aktuelle Daten', 'Porto-Ersparnis massiv', 'Garantierte Zustellung'], false),
      c('v5', 'Intelligenter Angebots-Nachfass', 'Erstellte Angebote werden oft nicht konsequent nachverfolgt, was wertvolles Potenzial liegen lässt.', 'Makler vergessen im Tagesgeschäft oft das Nachfassen. Hoher Marketing-Spend für Leads ohne konsequenten Abschluss.', 'KI fasst Angebote empathisch nach und klärt offene Fragen.', 'Die KI fragt nach dem Status der Entscheidung und bucht bei fachlichen Fragen sofort einen Termin mit dem Experten.', 'ArrowLeftRight', 'Connecting arrows digital', ['Conversion-Rate +30%', 'Entlastung der Makler', 'Maximierter Marketing ROI'], false)
    ]
  },
  {
    id: 'it_security',
    name: 'IT & Cybersecurity',
    iconName: 'Shield',
    cases: [
      c('s1', 'Simuliertes Deepfake Phishing', 'Mitarbeiter sind das größte Sicherheitsrisiko; Angriffe über KI-Stimmen nehmen massiv zu.', 'Social Engineering über das Telefon ist hocheffektiv. Passwörter oder Überweisungen werden am Telefon erschlichen.', 'KI führt kontrollierte, realistische Phishing-Tests durch.', 'Die KI ruft Mitarbeiter an, simuliert einen IT-Admin und schult bei Fehlverhalten sofort live im Gespräch für echte Resilienz.', 'ShieldAlert', 'Shield protecting brain', ['Maximale IT-Resilienz', 'Gelebte Sicherheitskultur', 'Compliance-Sicherung'], true),
      c('s2', 'Voice-ID Passwort-Reset', 'Der IT-Support ist zu 30% mit trivialen Passwort-Resets blockiert, was teure Ressourcen verschwendet.', 'Teure Administratoren erledigen Aufgaben, die automatisiert werden könnten. Mitarbeiter können während der Wartezeit nicht arbeiten.', 'KI setzt Passwörter nach sicherem Ident-Check (Voice-ID) zurück.', 'Die KI validiert Nutzer an der Stimme und Personalnummer und versendet neue Zugangsdaten sicher per SMS.', 'Key', 'Digital lock glowing', ['Support-Kosten -30%', 'Sofortige Hilfe 24/7', 'Admins fokussieren Core'], false),
      c('s3', 'KI-Inzidenz Alarmiersystem', 'Kritische IT-Alarme werden nachts oft übersehen, was zu massiven Downtime-Kosten führt.', 'E-Mails werden im Schlaf nicht gehört. Server-Ausfälle dauern oft Stunden bis zur Entdeckung. Hoher wirtschaftlicher Schaden.', 'KI ruft die IT-Bereitschaft bei kritischen Alarmen sofort an.', 'Die KI lässt das Telefon so lange klingeln, bis jemand abhebt und gibt technische Details des Fehlers live durch.', 'BellRing', 'Ringing digital bell', ['Minimale Downtime', 'Sicherer Bereitschaftsdienst', 'Reaktionszeit < 60s'], false),
      c('s4', 'Status-Hotline für Großstörungen', 'Bei IT-Großstörungen bricht die Telefonanlage durch tausende Anrufe von Mitarbeitern zusammen.', 'Alle Betroffenen rufen gleichzeitig an. Der Support kann keine Lösung erarbeiten, da er nur mit Telefonaten beschäftigt ist.', 'KI gibt Infos zur Störung und voraussichtlichen Entstörzeit.', 'Die KI erkennt den Standort des Nutzers und sagt: "Dein Office ist betroffen, wir arbeiten bereits an der Lösung".', 'Info', 'Digital info circle', ['Ruhe im Unternehmen', 'Support-Fokus auf Lösung', 'Höchste Transparenz'], false),
      c('s5', 'Multi-Faktor Voice-Auth', 'Hardware-Tokens sind teuer und werden oft vergessen oder gehen im Homeoffice verloren.', 'Mitarbeiter im Homeoffice benötigen sicheren Zugang. SMS-Codes gelten zunehmend als unsicher für High-Security Bereiche.', 'KI dient als zweiter Faktor via verschlüsseltem Voice-Anruf.', 'Der Nutzer erhält einen Anruf und muss eine PIN oder Phrase einsprechen – biometrisch und kryptografisch gesichert.', 'Lock', 'Digital padlock pulsing', ['Investitions-Ersparnis', 'Höchste Sicherheitsstufe', 'Einfachste Nutzer-UX'], false)
    ]
  },
  {
    id: 'logistics',
    name: 'Logistik & Transport',
    iconName: 'Truck',
    cases: [
      c('l_1', 'KI-Lieferstatus Auskunft', 'Kunden rufen ständig an: "Wo ist mein Paket?". Diese repetitiven Anfragen blockieren den Support.', '80% der Supportanfragen sind reine Status-Abfragen. Die manuelle Beantwortung kostet tausende Euro pro Monat.', 'KI gibt präzise Liefer-Infos basierend auf Echtzeit-GPS Daten.', 'Die KI informiert: "Dein Fahrer ist noch 3 Stationen entfernt, geschätzte Ankunft um 12:15 Uhr".', 'TruckIcon', 'Truck on data highway', ['-70% Support-Kosten', 'Herausragende User-UX', 'Echtzeit Tracking Voice'], true),
      c('l_2', 'Voice-gesteuerter Dispatcher', 'Disponenten verbringen zu viel Zeit mit der Durchgabe trivialer Anweisungen an das Fahrpersonal.', 'Adressänderungen oder Staus müssen einzeln durchgegeben werden. Hohe Fehlerquote und Ablenkung des Fahrers.', 'KI übermittelt neue Aufträge sprachgesteuert direkt an den Fahrer.', 'Der Fahrer bestätigt den Erhalt per Voice-Befehl – absolut freihändig und sicher während der Fahrt.', 'PhoneIncoming', 'Phone icon with arrow', ['Maximale Fahrer-Sicherheit', 'Hocheffiziente Disposition', 'Digitale Doku-Pflicht'], false),
      c('l_3', 'Dynamisches Rampen-Management', 'LKWs stauen sich vor dem Lager, da Ankunftszeiten oft nicht mit den gebuchten Slots übereinstimmen.', 'Fehlende Kommunikation zwischen Lager und Fahrer führt zu langen Wartezeiten und teuren Standgebühren.', 'KI koordiniert Ankunftszeiten live und autonom mit den Fahrern.', 'Die KI ruft Fahrer bei Verzögerungen an und schlägt neue, freie Zeitslots vor, um Staus an der Rampe zu vermeiden.', 'Container', 'Shipping containers digital', ['Optimale Rampenauslastung', 'Keine Standgebühren mehr', 'Stressfreies Lagerpersonal'], false),
      c('l_4', 'Mehrsprachiger Zoll-Assistent', 'Fehlende oder falsche Papiere an den Grenzen führen zu kostspieligem Stillstand der Flotte.', 'Fahrer verstehen oft die komplexen Dokumenten-Anforderungen nicht. LKWs hängen fest, Lieferketten reißen ab.', 'KI erklärt Zoll-Dokumente mehrsprachig und hilft beim Ausfüllen.', 'Die KI führt Fahrer durch die benötigten Unterlagen und versendet fehlende Informationen direkt per SMS-Link.', 'Globe', 'Digital globe connectivity', ['Grenzüberschreitung Pro', 'Minimierter Stillstand', 'Globaler Sprachservice'], false),
      c('l_5', 'KI-Fuhrpark Schadens-Doku', 'LKW-Schäden werden oft zu spät oder unklar gemeldet, was die Versicherungserstattung gefährdet.', 'Fuhrparkmanager erfahren oft erst Wochen später von Dellen. Ohne sofortige Doku reguliert die Versicherung oft nicht.', 'Fahrer diktieren Schäden sofort via Sprache an die KI-Zentrale.', 'Die KI fordert Fotos an, erstellt den Schadensbericht und informiert die Werkstatt zur Vorab-Teilebestellung.', 'Camera', 'Digital camera icon', ['Sichere Versicherungs-Doku', 'Top gepflegter Fuhrpark', 'Minimale Ausfallzeit'], false)
    ]
  },
  {
    id: 'automotive',
    name: 'Automotive Branche',
    iconName: 'Car',
    cases: [
      c('a1', 'Skalierbare Service-Terminierung', 'Kunden hängen während der Reifenwechsel-Saison in ewigen Warteschleifen der Autohäuser.', 'Das saisonale Peak-Volumen überfordert jede Telefonzentrale. Genervte Kunden rufen bei der nächsten freien Werkstatt an.', 'KI managt die komplette Werkstattplanung 24/7 vollautomatisch.', 'Die KI erkennt Kunden am Kennzeichen, prüft freie Hebebühnen und bucht Termine inkl. Leihwagen-Reservierung.', 'WrenchIcon', 'Modern car workshop', ['Keine verpassten Calls', 'Optimale Werkstatt-Auslastung', 'Enorme Büro-Entlastung'], true),
      c('a2', 'KI Leasing-Rückgabe Guide', 'Hohe Nachforderungen bei der Leasingrückgabe führen oft zu massivem Streit und Unzufriedenheit.', 'Kunden sind unvorbereitet auf Schäden am Fahrzeug. Der Prozess wird als intransparent und unfair empfunden.', 'KI führt Kunden vorab durch einen strukturierten Rückgabe-Check.', 'Die KI fragt Kilometerstände und Schäden ab, erklärt den Prozess und bucht bei Bedarf direkt einen Gutachter-Termin.', 'ClipboardCheck', 'Car silhouette with check', ['Transparentes Leasing', 'Minimierte Reklamationen', 'Top Service-Vorteil'], false),
      c('a3', 'KI Probefahrt-Lead Turbo', 'Interessenten auf Portalen werden oft zu spät zurückgerufen, was die Kaufwahrscheinlichkeit senkt.', 'Das Kaufinteresse kühlt nach 30 Minuten massiv ab. Verkäufer schaffen den Rückruf im Tagesgeschäft oft nicht zeitnah.', 'KI ruft Leads in unter 60s an und vereinbart die Probefahrt.', 'Die KI qualifiziert das Modell-Interesse vorab und trägt den Termin direkt in den Kalender des zuständigen Verkäufers ein.', 'Target', 'Digital target bullseye', ['Sales-Uplift massiv', 'Beste Kundenerfahrung', 'Top Marketing-ROI'], false),
      c('a4', 'Intelligente Pannen-Notruf Zentrale', 'Standard-Pannennotrufe blockieren oft lebenswichtige Rettungssysteme in Autohäusern oder Clubs.', 'Fragen zu Reifenpannen landen oft in der gleichen Leitung wie schwere Unfälle. Echte Notfälle müssen warten.', 'KI trennt technische Pannen von echten medizinischen Notfällen.', 'Die KI leitet technische Pannen an Service-Partner weiter, medizinische Notfälle werden sofort an die 112 durchgestellt.', 'Siren', 'Blue emergency light', ['Echte Lebensrettung', 'Effiziente Hilfeleistung', 'Enorme Kosten-Ersparnis'], false),
      c('a5', 'Proaktiver Zubehör-Sales Agent', 'Das enorme Potenzial für Zusatzverkäufe (Winterreifen, Dachboxen) bleibt oft völlig ungenutzt.', 'Autohäuser schaffen es personell nicht, Kunden nach dem Kauf proaktiv zu kontaktieren. Umsatzpotenziale liegen brach.', 'KI informiert Kunden über perfekt passende Angebote nach dem Kauf.', 'Die KI kontaktiert Kunden: "Deine passenden Winterreifen sind jetzt im Angebot. Soll ich sie für dich reservieren?".', 'BoxSelect', 'Car parts digital flow', ['Zusatzumsatz generiert', 'Hohe Kundenbindung', 'Individueller Service'], false)
    ]
  },
  {
    id: 'education',
    name: 'Bildung & Coaching',
    iconName: 'EducationIcon',
    cases: [
      c('ed1', 'Individueller KI-Lern-Coach', 'Lehrer können in Klassen mit 30 Schülern nicht auf individuelle Wissenslücken eingehen.', 'Schüler bleiben bei Problemen hängen und verlieren die Motivation. Eine individuelle Förderung ist personell kaum leistbar.', 'KI agiert als geduldiger, fachlich versierter 24/7 Voice-Tutor.', 'Schüler führen Fachgespräche mit der KI. Die KI erkennt Lücken, erklärt Konzepte neu und gibt gezielte Hilfestellungen.', 'GraduationCap', 'Digital brain with cap', ['Maximale Lernförderung', 'Immer verfügbar 24/7', 'Massive Lehrer-Entlastung'], true),
      c('ed2', 'KI Sekretariats-Automatisierung', 'Die morgendliche Flut an Krankmeldungen blockiert die Schulsekretariate für Stunden.', 'Zwischen 7:30 und 8:30 Uhr gehen hunderte Anrufe ein. Sekretariate sind lahmgelegt für dringende Notfälle.', 'KI nimmt alle Krankmeldungen an und dokumentiert diese digital.', 'Die KI erkennt Namen und Klasse fehlerfrei und informiert die entsprechenden Lehrer sofort via Push-Nachricht.', 'ClipboardList', 'Digital list with checks', ['Stressfreier Schulmorgen', 'Sichere Doku-Pflicht', 'Sofort-Info für Lehrer'], false),
      c('ed3', 'KI-Sprachpartner für Fremdsprachen', 'Schülern fehlt im Alltag die nötige Praxis, um eine Fremdsprache wirklich flüssig sprechen zu lernen.', 'Im Unterricht wird zu wenig gesprochen, da die Zeit fehlt. Die Hemmschwelle für Dialoge ist bei Schülern oft hoch.', 'KI ist der native Gesprächspartner für Englisch, Spanisch & Co.', 'Schüler führen natürliche Dialoge mit der KI in der Zielsprache. Die KI korrigiert Grammatik und Aussprache sanft im Flow.', 'Languages', 'Speech bubbles with flags', ['Flüssiges Sprechen lernen', 'Keine Angst vor Fehlern', 'Echte Sprachpraxis'], false),
      c('ed4', 'Akademische Kurs-Beratung', 'Interessenten für Weiterbildungen brauchen Beratung, die außerhalb der Bürozeiten oft nicht verfügbar ist.', 'Webseiten sind oft zu komplex. Potenzielle Studenten springen ab, wenn sie ihre spezifischen Fragen nicht sofort klären können.', 'KI berät zu Kursinhalten, Zulassungen und Abschlüssen.', 'Die KI fragt Vorwissen und Ziele ab und empfiehlt den passenden akademischen Karriere-Pfad – auch am Wochenende.', 'BookOpen', 'Digital book glowing', ['Höhere Buchungsquoten', 'Premium Service 24/7', 'Hocheffiziente Beratung'], false),
      c('ed5', 'Automatisierter Alumni-Netzwerk Agent', 'Hochschulen verlieren oft nach dem Abschluss den Kontakt zu ihren wertvollen Absolventen.', 'Die manuelle Pflege des Netzwerks ist zu teuer. Das Spenden- und Kooperationspotenzial bleibt oft völlig ungenutzt.', 'KI hält den Kontakt zu Ehemaligen und sammelt Karriere-Updates.', 'Die KI ruft Absolventen an, gratuliert zu Karriereschritten und lädt zu exklusiven Alumni-Events der Hochschule ein.', 'Award', 'Digital trophy with network', ['Starkes Alumni-Netzwerk', 'Marketing-Power Boost', 'Effizientes Fundraising'], false)
    ]
  },
  {
    id: 'energy',
    name: 'Energie & Versorger',
    iconName: 'PowerIcon',
    cases: [
      c('en1', 'Zählerstand-Erfassung per Voice', 'Der Jahreswechsel-Stress durch manuelle Zählerstand-Meldungen bindet enorme Ressourcen.', 'Fehleingaben am Telefon durch Hörfehler und hohe Personalkosten für die Eingabe. Kunden sind von besetzten Leitungen genervt.', 'KI nimmt Zählerstände per Voice auf und validiert diese live.', 'Die KI erkennt Plausibilitätsfehler ("Stand niedriger als im Vorjahr") sofort im Gespräch und klärt den Fehler direkt.', 'Gauge', 'Utility meter digital pulse', ['Null Fehlerrate Daten', 'Extreme Kostensenkung', '24/7 Kunden-Service'], true),
      c('en2', 'KI Störungs-Management', 'Großflächige Stromausfälle führen zu tausenden gleichzeitigen Anrufen, die kein Callcenter händeln kann.', 'Netzbetreiber können das Volumen nicht bewältigen. Bürger bleiben ohne Information, was die Verunsicherung massiv erhöht.', 'KI gibt standortbezogene Informationen zur Entstörung aus.', 'Die KI erkennt die Anrufer-PLZ automatisch: "Der Kabelschaden ist bekannt, Reparatur erfolgt voraussichtlich bis 14 Uhr".', 'Siren', 'Glowing lightbulb storm', ['Sicherheit durch Info', 'Entlastung der Leitwarte', 'Echtzeit-Information'], false),
      c('en3', 'Proaktive Tarif-Wechsel Beratung', 'Kunden kündigen ihre Verträge massenhaft nach Preiserhöhungen, was zu einem hohen Churn führt.', 'Preisanpassungen führen zu Kündigungswellen. Der Support kann nicht jeden Kunden individuell halten und beraten.', 'KI klärt Gründe für Unzufriedenheit und bietet bessere Tarife an.', 'Die KI analysiert den Verbrauch und bietet individuelle Rabatte oder Tarif-Modelle zur Kundenbindung direkt im Gespräch an.', 'RefreshCcw', 'Energy cycle digital', ['Churn-Rate -20%', 'Umsatzsicherung massiv', 'Hohe Kundenloyalität'], false),
      c('en4', 'Handwerker-Portal Telefon-Support', 'Einspeisewünsche für PV-Anlagen überfordern den Innendienst durch unvollständige Anträge.', 'Anträge von Elektrikern sind oft unvollständig. Das mühsame Nachfordern von Daten kostet oft viele Wochen Zeit.', 'KI telefoniert Elektriker für fehlende technische Daten ab.', 'Die KI fragt technische Parameter der PV-Anlage ab und vervollständigt den Antrag für eine schnellere Netzfreigabe.', 'Sun', 'Digital sun with data', ['Schnellerer Netzanschluss', 'Zufriedene Fachpartner', 'Energiewende-Beschleunigung'], false),
      c('en5', 'Automatisierte Ratenzahlungs-Pläne', 'Hohe Nachzahlungen nach der Jahresrechnung führen oft zu Zahlungsausfällen bei Privatkunden.', 'Kunden können hohe Einmalbeträge oft nicht leisten. Manuelle Ratenplanungen sind für Versorger oft zu teuer in der Verwaltung.', 'KI vereinbart Ratenzahlungen autonom direkt am Telefon.', 'Die KI errechnet faire Raten basierend auf dem Einkommen und den Vorgaben und bucht diese sofort rechtssicher im System.', 'CreditCard', 'Digital money flow', ['Liquiditätssicherung', 'Weniger Inkasso-Fälle', 'Hohe soziale Kompetenz'], false)
    ]
  },
  {
    id: 'gov',
    name: 'Öffentlicher Sektor',
    iconName: 'GovIcon',
    cases: [
      c('gv1', 'Digitaler Bürger-Service Assistent', 'Bürgerämter sind für ihre schlechte telefonische Erreichbarkeit bekannt, was zu Frust führt.', 'Einfache Standardfragen verstopfen die Leitungen für komplexe soziale Notfälle. Die Verwaltung wirkt modernisierungsbedürftig.', 'KI beantwortet Standardfragen und bucht verbindliche Termine.', 'Die KI kennt alle Satzungen und benötigten Dokumente für Anträge und hilft Bürgern rund um die Uhr, 7 Tage die Woche.', 'Landmark', 'Historic building digital', ['Zufriedene Bürger-Erfahrung', 'Massive Kostensenkung', 'Digitale Transformation'], true),
      c('gv2', 'Automatisierte Wahlhelfer-Akquise', 'Die Suche nach Freiwilligen für Wahlen ist ein mühsamer, manueller Prozess für die Kommunen.', 'Mitarbeiter telefonieren tagelang Listen ab, die Erfolgsquote ist gering bei gleichzeitig extrem hohen Personalkosten.', 'KI telefoniert potenzielle Wahlhelfer ab und plant den Einsatz.', 'Die KI klärt die Verfügbarkeit, den Einsatzort und versendet Schulungsunterlagen automatisiert nach der Zusage.', 'Users', 'Digital crowd network', ['Voll besetzte Wahllokale', 'Null manueller Aufwand', 'Strukturierte Planung'], false),
      c('gv3', 'Intelligenter Abfall-Informationsdienst', 'Hunderte Anfragen zu Verschiebungen der Müllabfuhr nach Feiertagen blockieren die Ämter.', 'Feiertage führen zu Verwirrung bei den Bürgern. Viele greifen zum Telefon, statt die App oder das Web zu nutzen.', 'KI gibt Entsorgungstermine basierend auf der Adresse durch.', 'Die KI informiert präzise: "Deine Biotonne wird wegen Ostern erst am Mittwoch geleert, bitte stell sie rechtzeitig raus".', 'TruckIcon', 'Waste truck digital', ['Support-Entlastung 80%', 'Hervorragende Bürger-Info', 'Moderner Service'], false),
      c('gv4', 'KI-gestütztes Fundbüro-Management', 'Bürger rufen täglich an, um nach verlorenen Gegenständen zu fragen, was viel Personalzeit bindet.', 'Personal verbringt viel Zeit mit der manuellen Suche in Listen für Kleinteile (Schlüssel, Schirme, Handys).', 'KI gleicht Verlustmeldungen mit der Fund-Datenbank live ab.', 'Die KI klärt Details ("Welche Farbe hat dein Schlüssel?") ab und vereinbart bei Erfolg sofort einen Abholtermin.', 'Search', 'Magnifying glass glowing', ['Personal-Entlastung pur', 'Sehr glückliche Bürger', 'Vollständig Digitale Liste'], false),
      c('gv5', 'Krisen-Kommunikations Zentrale', 'Großschadenslagen wie Hochwasser erfordern eine sofortige Massen-Information der Bevölkerung.', 'Katastrophenfälle überlasten die Telefonleitungen der Behörden innerhalb von Minuten. Bürger erhalten keine Infos.', 'KI übernimmt hunderte Telefonate gleichzeitig zur Lage-Information.', 'Die KI gibt Verhaltenshinweise, warnt vor Gefahrenzonen und entlastet so die Notrufnummern 110 und 112.', 'Siren', 'Flood warning digital', ['Aktiver Bevölkerungsschutz', 'Informations-Souveränität', 'Entlastung der Notrufe'], false)
    ]
  },
  {
    id: 'tourism',
    name: 'Tourismus & Freizeit',
    iconName: 'Globe',
    cases: [
      c('tm1', 'Intelligenter Reise-Verkaufsberater', 'Komplexe Online-Buchungen brechen bei Detailfragen oft ab, da keine sofortige Hilfe verfügbar ist.', 'Kunden sind unsicher bei Versicherungen oder Hoteldetails und brechen den Kaufprozess entnervt ab. Umsatz geht verloren.', 'KI-Voice Begleiter führt Kunden sicher durch den Buchungsprozess.', 'Die KI fungiert als digitaler Reisebüro-Profi, klärt Details am Telefon und schließt den Kauf direkt rechtsverbindlich ab.', 'Umbrella', 'Globe with flight paths', ['Conversion-Rate +25%', 'Weniger Warenkorb-Abbrüche', 'Top Service-Vorteil'], true),
      c('tm2', 'Persönlicher 24/7 City-Guide', 'Geführte Touren sind unflexibel und für viele Touristen zu teuer oder zeitlich nicht passend.', 'Touristen wünschen sich Informationen genau dann, wenn sie vor einer Sehenswürdigkeit stehen – nicht erst am Abend im Hotel.', 'KI agiert als persönlicher, interaktiver Guide direkt im Ohr des Touristen.', 'Per Standortfreigabe erzählt die KI spannende Geschichten zu Gebäuden und bucht bei Bedarf Tickets direkt via Sprachbefehl.', 'Map', 'Digital map with points', ['Individuelles Erlebnis', 'Unbegrenzt Skalierbar', 'Zusatzumsatz Affiliate'], false),
      c('tm3', 'Automatisierte Flug-Umbuchung', 'Chaos bei Flugverspätungen sorgt für endlose Schlangen am Schalter und extremen Passagier-Frust.', 'Tausende Fluggäste wollen gleichzeitig Informationen und eine Umbuchung. Das Bodenpersonal ist in diesen Situationen hoffnungslos überlastet.', 'KI managt Umbuchungen für hunderte Passagiere zeitgleich via Voice.', 'Die KI prüft Alternativverbindungen, bucht den Gast um und versendet das neue Ticket sofort direkt auf das Smartphone.', 'Send', 'Paper plane digital', ['Kein Stress am Gate', 'Enorme Kosten-Ersparnis', 'Starker UX-Vorteil'], false),
      c('tm4', 'Echtzeit Ski-Resort Info-Bot', 'Standardfragen zu Pisten und Liften blockieren die Mitarbeiter im Tourismusbüro bei starkem Andrang.', 'Skifahrer wollen morgens schnell wissen: "Ist die Talabfahrt offen?". Die Telefonleitungen stehen bei Neuschnee nie still.', 'KI gibt präzise Echtzeit-Berichte über Pisten und Lifte via Voice.', 'Die KI kennt das aktuelle Wetter, die Windgeschwindigkeiten und den Öffnungsstatus aller Anlagen am Berg.', 'Snowflake', 'Ski lift with data dots', ['Informationskanal 24/7', 'Sicherheit für Skifahrer', 'Modernes Resort-Image'], false),
      c('tm5', 'Digitaler Visa- & Einreise-Assistent', 'Reisende sind oft unsicher über aktuelle Bestimmungen, was zu Problemen am Flughafen führt.', 'Mails an Konsulate werden oft nicht beantwortet. Die Angst vor Fehlern bei der Einreise ist bei Fernreisen sehr hoch.', 'KI klärt Einreise-Voraussetzungen basierend auf dem Reisepass.', 'Die KI prüft den Impfstatus, die Visa-Pflicht und die Gültigkeit des Passes in einem kurzen, interaktiven Dialog.', 'FileSignature', 'Digital passport glowing', ['Sorgenfreies Reise-Erlebnis', 'Exklusiver Service-Vorteil', 'Automatisierte Doku-Prüfung'], false)
    ]
  },
  {
    id: 'marketing',
    name: 'Marketing & Agenturen',
    iconName: 'IdeaIcon',
    cases: [
      c('m1', 'Ultra-Fast Termin-Turbo', 'Web-Leads werden manuell oft erst nach Stunden kontaktiert, wodurch die Abschlusschance rapide sinkt.', 'Wird ein Lead nicht innerhalb von 15 Minuten angerufen, sinkt die Wahrscheinlichkeit eines Abschlusses um über 80%.', 'KI ruft jeden qualifizierten Lead sofort an und setzt den Termin.', 'Die KI agiert als digitaler SDR, qualifiziert das Interesse und bucht den Kalender des Closers voll – noch während der Lead auf der Website ist.', 'Target', 'Digital target bullseye', ['Maximale Lead-Effizienz', 'Massiv gesteigerter Umsatz', 'Fokus auf das Closing'], true),
      c('m2', 'Qualitative NPS-Voice Umfragen', 'Schriftliche Umfragen haben eine geringe Rücklaufquote und liefern oft keine tiefen, qualitativen Insights.', 'Unternehmen wissen oft nicht, was ihre Kunden wirklich denken. Standard-Mails werden massenhaft ignoriert.', 'KI führt kurze, strukturierte Feedback-Calls für echtes Kunden-Feedback.', 'Die KI erkennt Stimmungen in der Stimme und transkribiert qualitative Insights für die Strategie-Optimierung im CRM.', 'PieChart', 'Bar chart digital pulse', ['Echte Kunden-Insights', 'Hohe Rücklaufquoten', 'Wertvolle CRM-Daten'], false),
      c('m3', 'Automatisierter Event-Reminder', 'Hohe No-Show Quoten bei kostenlosen Webinaren oder Events entwerten den Marketing-Spend massiv.', 'Kostenlose Online-Events werden oft vergessen. Das Investment in das Marketing verpufft ohne Teilnehmer am Tag X.', 'KI ruft Teilnehmer kurz vor dem Event an und steigert die Vorfreude.', 'Die KI erinnert an die Startzeit, klärt letzte technische Fragen zum Zugang und erhöht so die Teilnehmerrate signifikant.', 'BellRing', 'Ringing bell digital', ['No-Show Quote -40%', 'Deutlich mehr Teilnehmer', 'Maximierter Marketing ROI'], false),
      c('m4', 'Predictive Win-Back Calls', 'Inaktive Altkunden werden manuell fast nie reaktiviert, obwohl dies günstiger ist als Neukundenakquise.', 'Marketing-Daten zeigen die Inaktivität, aber niemand im Team hat die Zeit für Reaktivierungs-Calls. Potenziale bleiben liegen.', 'KI kontaktiert inaktive Altkunden mit einem individuellen Angebot.', 'Die KI bietet personalisierte Rabatte basierend auf der Kaufhistorie an, um den Kunden zurückzugewinnen.', 'Repeat', 'Rotating arrows digital', ['Reaktivierungs-Uplift massiv', 'Customer Lifetime Value +', 'Automatisierte Retention'], false),
      c('m5', 'KI Affiliate-Onboarding Bot', 'Neue Partner und Affiliates wissen oft nicht, wie sie starten sollen, was den Sales-Start verzögert.', 'Eine manuelle Betreuung für hunderte kleine Partner ist personell unmöglich. Viele Potenziale werden so nie aktiviert.', 'KI begleitet neue Partner empathisch durch die ersten Schritte.', 'Die KI erklärt das Dashboard, verfügbare Werbemittel und das Provisionsmodell in einem persönlichen Telefonat.', 'Handshake', 'Glowing handshake digital', ['Deutlich schnellere Sales', 'Starke Partner-Loyalität', 'Skalierung ohne Headcount'], false)
    ]
  },
  {
    id: 'wellness',
    name: 'Fitness & Lifestyle',
    iconName: 'WellnessIcon',
    cases: [
      c('w1', '24/7 Studio-Mitgliedschafts Agent', 'Interessenten rufen oft an, wenn kein geschultes Beratungspersonal im Fitnessstudio vor Ort ist.', 'Am Abend oder Wochenende ist oft nur Trainingspersonal da. Verkäufe von Mitgliedschaften gehen so massiv verloren.', 'KI berät Interessenten zu Tarifen und schließt Verträge rechtssicher ab.', 'Die KI erklärt die Vorteile der verschiedenen Pakete und versendet den Vertrag sofort per SMS-Link zur Unterschrift.', 'Dumbbell', 'Muscular arm digital', ['Umsatzgenerierung 24/7', 'Entlastung Trainer-Team', 'Vollautomatische Sales'], true),
      c('w2', 'KI Spa-Ressourcen Planung', 'Die Buchung komplexer Wellness-Pakete am Telefon dauert manuell zu lange und ist fehleranfällig.', 'Kunden wollen Massage + Sauna + Treatment. Die manuelle Abstimmung von Räumen und Therapeuten ist ein logistisches Puzzle.', 'KI koordiniert alle Ressourcen und bucht den perfekten Wellness-Tag.', 'Die KI prüft die Verfügbarkeit von Raum und Personal in Echtzeit und bestätigt den Slot verbindlich im Gespräch.', 'Waves', 'Blue waves digital', ['Optimale Raumauslastung', 'Keine Fehlbuchungen mehr', 'Premium Service-Vorgang'], false),
      c('w3', 'Churn-Prävention für Studios', 'Mitglieder kündigen oft stillschweigend, weil sie über längere Zeit nicht mehr zum Training erschienen sind.', 'Stumme Kündigungen sind der Profit-Killer in der Fitnessbranche. Niemand bemerkt die Inaktivität rechtzeitig für ein Gegensteuern.', 'KI ruft inaktive Mitglieder empathisch an und motiviert zum Neustart.', 'Die KI bietet ein kostenloses Personal Training oder einen Body-Check-up an, um das Mitglied wieder zu aktivieren und zu binden.', 'RefreshCcw', 'Cycle with heart', ['Churn-Rate -15% gesichert', 'Echte Community-Bindung', 'Mehr Profitabilität'], false),
      c('w4', 'Intelligenter Kurs-Wartelisten Manager', 'Kurse sind oft ausgebucht, aber Teilnehmer erscheinen nicht, wodurch Plätze ungenutzt bleiben.', 'Der Yoga-Raum ist oft halb leer trotz langer Warteliste. Das sorgt für Enttäuschung bei allen Beteiligten.', 'KI telefoniert die Warteliste bei Absagen in Echtzeit autonom ab.', 'Die KI ruft den nächsten auf der Liste an: "Ein Platz ist frei geworden! Kommst du?". So bleibt jeder Kurs maximal belegt.', 'Users', 'Digital group in yoga pose', ['Maximale Kursauslastung', 'Hochzufriedene Mitglieder', 'Effizienz in der Planung'], false),
      c('w5', 'Automatisierter Ernährungs-Check-in', 'Mitglieder verlieren oft die Motivation zwischen den Terminen, was zu ausbleibenden Erfolgen führt.', 'Der Erfolg bleibt aus, die Kündigung folgt. Eine engmaschige Betreuung ist personell für die meisten Studios zu teuer.', 'KI führt wöchentliche Check-in Calls zu den gesetzten Zielen durch.', 'Die KI fragt Fortschritte ab, gibt kleine Tipps und vereinbart den nächsten wichtigen Termin direkt im Fitnessstudio.', 'Apple', 'Digital apple glowing', ['Sichtbarer Trainingserfolg', 'Extrem hohe Mitgliederbindung', 'Premium-Image'], false)
    ]
  },
  {
    id: 'specialized',
    name: 'Media & Agriculture',
    iconName: 'IdeaIcon',
    cases: [
      c('x1', 'Abonnenten-Rückgewinnungs Agent', 'Zeitungs-Abos werden oft impulsiv online gekündigt, was zu hohen Verlusten bei den Verlagen führt.', 'Der Verlust langjähriger Leser schmerzt. E-Mails zur Rückgewinnung werden oft ignoriert und erzielen kaum Wirkung.', 'KI ruft gekündigte Abonnenten an und klärt die Beweggründe.', 'Die KI bietet individuelle Probe-Abos oder exklusive digitale Upgrades zur Bindung direkt am Telefon an.', 'Newspaper', 'Newspaper rolls digital', ['Storno-Rettung +20%', 'Tiefe Leser-Insights', 'ROI-Boost Abo-Modell'], true),
      c('x2', 'Breaking-News VIP Alarm', 'Wichtige Nachrichten gehen in der Masse der Push-Benachrichtigungen oft völlig unter.', 'Premium-Leser zahlen für Exklusivität und sofortige Information bei Top-Events. Eine App-Benachrichtigung reicht hier oft nicht aus.', 'KI ruft VIP-Leser bei Breaking News proaktiv für eine Kurzzusammenfassung an.', 'Die KI gibt ein kurzes Audio-Update der Lage und bietet einen SMS-Link zum exklusiven Hintergrundartikel an.', 'Tv', 'Digital screen pulsing', ['Maximale Aufmerksamkeit', 'Echtes Premium-Feature', 'Abo-Mehrwert massiv'], false),
      c('x3', 'KI Erntehelfer Koordinator', 'Die Koordination von hunderten Saisonkräften ist ein logistisches Chaos für landwirtschaftliche Betriebe.', 'Sprachbarrieren und ständig wechselnde Wetterbedingungen überfordern die Betriebsleiter in der Hochsaison massiv.', 'KI koordiniert Erntehelfer mehrsprachig und hocheffizient am Telefon.', 'Die KI gibt Einsatzorte und Zeiten in der Muttersprache durch und sammelt Bestätigungen für die Einsatzplanung.', 'Tractor', 'Tractor in digital field', ['Sichere Ernte-Logistik', 'Keine Sprachbarrieren mehr', 'Hocheffiziente Planung'], false),
      c('x4', 'Veterinär Notruf-Priorisierung', 'Tierärzte sind bei Notfällen im Stall oft schwer erreichbar, was wertvolle Zeit kostet.', 'Jede Minute zählt bei kranken Tieren in der Landwirtschaft. Die Praxis-Zentrale ist oft nicht rund um die Uhr besetzt.', 'KI priorisiert Tier-Notfälle und alarmiert den zuständigen Arzt sofort.', 'Die KI klärt Symptome am Telefon ab und alarmiert den Diensthabenden sofort per Priority-Anruf auf dem Handy.', 'Stethoscope', 'Digital paw icon', ['Tierwohl-Garantie', '24/7 Notdienst-Sicherheit', 'Stress-Senkung Team'], false),
      c('x5', 'KI Agrar-Wetter Warnsystem', 'Unwetterwarnungen müssen sofort auf dem Feld ankommen, um Schäden an Ernten zu minimieren.', 'Landwirte sehen Warn-Apps bei der harten Arbeit oft zu spät. Hagel oder Frost führen so oft zu totalen Ernteverlusten.', 'KI ruft den Landwirt bei drohenden Gefahren sofort persönlich an.', 'Die KI gibt präzise Warnungen und Zeitfenster für Schutzmaßnahmen durch, um die Ernte aktiv zu sichern.', 'CloudRain', 'Rain and lightning digital', ['Aktiver Ernteschutz', 'Echtzeit-Warnung Voice', 'Haftungs-Prävention'], false)
    ]
  }
];
